version: '3.7'

volumes:
  datastore:
  node-rest:

services:
  datastore:
    image: dergons/datastore-emulator
    volumes:
      - datastore:/opt/data
    environment:
      - DATASTORE_PROJECT_ID=gcp-project
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8081
    ports:
      - "8081:8081"

  datastore-viewer:
    image: shghe/datastore-viewer
    environment:
      - DSVIEWER_PROJECT_ID=gcp-project
      - DSVIEWER_PORT=8282
      - DSVIEWER_DATASTORE_ENDPOINT=datastore:8081
    ports:
      - 8282:8282
    depends_on:
      - datastore
    links:
      - datastore

  message-service:
    build: ./Message-service
    image : rest-api
    volumes:
      - ./Message-service/files/src:/src
      - node-rest:/src/node_modules/
    ports:
      - 3003:3000
    command: ['nodemon', 'server.js']
    environment:
      - PROJECT_ID=gcp-project
      - DATASTORE_PORT=8081
      - DATASTORE_HOST=datastore
      - NODE_ENV=local-development
      - DO_DOWNSTREAM_AUTH=false
    depends_on:
      - datastore
